### ISSUE TITLE
Android device facing SQLiteException(Can't downgrade database from version 2 to 1)

### ISSUE THREAD

**Issue by samclam** [cashfree/flutter-cashfree-pg-sdk#10]
Hi team,

i am getting SQLiteException exception when app is opened.

**Plugin version:**  2.0.1+4

**Log**

`E/AndroidRuntime(24564): android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
E/AndroidRuntime(24564): 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540)
E/AndroidRuntime(24564): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
E/AndroidRuntime(24564): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
E/AndroidRuntime(24564): 	at com.cashfree.pg.analytics.database.CFDatabaseService.lambda$checkIfPaymentsPresent$3$CFDatabaseService(Unknown Source:2)
E/AndroidRuntime(24564): 	at com.cashfree.pg.analytics.database.-$$Lambda$CFDatabaseService$DscKZq0oUzPPdCcoRl_XPVTLWpg.run(Unknown Source:4)
E/AndroidRuntime(24564): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(24564): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(24564): 	at java.lang.Thread.run(Thread.java:1012)`

**Comment by samclam** [comment]
Implementation issue
