### ISSUE TITLE
Crash Report - flutter_cashfree_pg_sdk: ^2.1.2+32

### ISSUE THREAD

**Issue by qube-dev-tejas** [cashfree/flutter-cashfree-pg-sdk#64]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
       at com.cashfree.pg.core.api.ui.receiver.CFSMSBroadcastReceiver.onReceive(CFSMSBroadcastReceiver.java:41)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by kishan-cashfree** [comment]
@qube-dev-tejas 
Please update to the latest SKD version 2.1.6+36

**Comment by kishan-cashfree** [comment]
Please reopen if you face this issue again.
@qube-dev-tejas
