### ISSUE TITLE
Fatal exception on lower android version

### ISSUE THREAD

**Issue by rishi2896** [cashfree/flutter-cashfree-pg-sdk#65]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
       at com.cashfree.pg.core.api.ui.receiver.CFSMSBroadcastReceiver.onReceive(CFSMSBroadcastReceiver.java:41)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
       
**Device**

Brand:Google
Model:Nexus 5X
Orientation:Portrait
RAM free: 1.32 GB
Disk free: 356.58 MB

**Operating System**
Version:Android 8.1.0
Orientation:Portrait
Rooted: No

**Comment by kishan-cashfree** [comment]
@rishi2896  Please share the SDK version

**Comment by kishan-cashfree** [comment]
@rishi2896 Also please share the lower version details.

**Comment by rishi2896** [comment]
@kishan-cashfree      
 minSdkVersion 21
targetSdkVersion 34
compileSdkVersion 34


flutter_cashfree_pg_sdk: ^2.1.3+33

**Comment by kishan-cashfree** [comment]
@rishi2896 Can you please update to the latest SDK version 
https://pub.dev/packages/flutter_cashfree_pg_sdk/versions

This is already fixed in the latest SDK versions.

**Comment by rishi2896** [comment]
@kishan-cashfree sure let me check.

**Comment by kishan-cashfree** [comment]
Please reopen if you face the same issue again.

You can join our discord channel for quicker resolution.
https://discord.gg/g6WhD7H9
